"""initial postgres schema

Revision ID: 45535e6bdd80
Revises: 
Create Date: 2026-08-19 23:43:17.982073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45535e6bdd80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_mapping_rule',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('kategori_transaksi', sa.String(), nullable=False),
    sa.Column('event_trigger', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('kode_debet', sa.String(), nullable=False),
    sa.Column('nama_akun_debet', sa.String(), nullable=False),
    sa.Column('kode_kredit', sa.String(), nullable=False),
    sa.Column('nama_akun_kredit', sa.String(), nullable=False),
    sa.Column('trigger_dokumen', sa.String(), nullable=True),
    sa.Column('aturan_keterangan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_salt', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('kode_akun', sa.String(), nullable=False),
    sa.Column('nama_akun', sa.String(), nullable=False),
    sa.Column('penjelasan_awam', sa.Text(), nullable=True),
    sa.Column('kelompok_utama', sa.String(), nullable=False),
    sa.Column('saldo_normal', sa.String(), nullable=True),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('is_header', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'kode_akun', name='uq_account_owner_kode_akun')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('rule_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_no'], ['transaction_mapping_rule.no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_expense_date'), 'expense', ['expense_date'], unique=False)
    op.create_table('omni_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('platform_order_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('fulfillment_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_status', sa.String(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('customer_ref', sa.String(), nullable=True),
    sa.Column('payout_batch_ref', sa.String(), nullable=True),
    sa.Column('gross_amount', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'platform_order_id', name='uq_omni_order_owner_platform_order_id')
    )
    op.create_index(op.f('ix_omni_order_channel'), 'omni_order', ['channel'], unique=False)
    op.create_index(op.f('ix_omni_order_order_time'), 'omni_order', ['order_time'], unique=False)
    op.create_index(op.f('ix_omni_order_status'), 'omni_order', ['status'], unique=False)
    op.create_table('password_reset_token',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('platform',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fulfillment_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fee_rate', sa.Float(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'code', name='uq_platform_owner_code')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('ppn_rate', sa.Float(), nullable=True),
    sa.Column('cogs_price', sa.Float(), nullable=False),
    sa.Column('unit_label', sa.String(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'sku', name='uq_product_owner_sku')
    )
    op.create_table('settlement',
    sa.Column('settlement_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('platform_order_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('payout_amount', sa.Float(), nullable=False),
    sa.Column('diff_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('batch_ref', sa.String(), nullable=True),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('settlement_id')
    )
    op.create_index(op.f('ix_settlement_platform_order_id'), 'settlement', ['platform_order_id'], unique=False)
    op.create_index(op.f('ix_settlement_settlement_date'), 'settlement', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_settlement_status'), 'settlement', ['status'], unique=False)
    op.create_table('journal_entry',
    sa.Column('no_jurnal', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('kode_debet', sa.String(), nullable=False),
    sa.Column('nama_akun_debet', sa.String(), nullable=False),
    sa.Column('kode_kredit', sa.String(), nullable=False),
    sa.Column('nama_akun_kredit', sa.String(), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('sumber_dokumen', sa.String(), nullable=True),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rule_no', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('settlement_id', sa.String(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_no'], ['transaction_mapping_rule.no'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.settlement_id'], ),
    sa.PrimaryKeyConstraint('no_jurnal')
    )
    op.create_index(op.f('ix_journal_entry_created_time'), 'journal_entry', ['created_time'], unique=False)
    op.create_index(op.f('ix_journal_entry_tanggal'), 'journal_entry', ['tanggal'], unique=False)
    op.create_table('omni_order_fee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['omni_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('omni_order_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('platform_item_id', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('modifiers', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['omni_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('changed_fields', sa.Text(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('changed_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_audit_log_changed_time'), 'product_audit_log', ['changed_time'], unique=False)
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_platform_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('platform_item_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('change_qty', sa.Integer(), nullable=False),
    sa.Column('resulting_qty', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movement_created_time'), 'stock_movement', ['created_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movement_created_time'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_table('product_platform_mapping')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_product_audit_log_changed_time'), table_name='product_audit_log')
    op.drop_table('product_audit_log')
    op.drop_table('omni_order_item')
    op.drop_table('omni_order_fee')
    op.drop_index(op.f('ix_journal_entry_tanggal'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_created_time'), table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index(op.f('ix_settlement_status'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_settlement_date'), table_name='settlement')
    op.drop_index(op.f('ix_settlement_platform_order_id'), table_name='settlement')
    op.drop_table('settlement')
    op.drop_table('product')
    op.drop_table('platform')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('ix_omni_order_status'), table_name='omni_order')
    op.drop_index(op.f('ix_omni_order_order_time'), table_name='omni_order')
    op.drop_index(op.f('ix_omni_order_channel'), table_name='omni_order')
    op.drop_table('omni_order')
    op.drop_index(op.f('ix_expense_expense_date'), table_name='expense')
    op.drop_table('expense')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('transaction_mapping_rule')
    # ### end Alembic commands ###
