"""add error_log table

Revision ID: 58329ba87cc6
Revises: 45535e6bdd80
Create Date: 2026-08-20 21:19:28.429609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58329ba87cc6'
down_revision: Union[str, Sequence[str], None] = '45535e6bdd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_log_created_at'), 'error_log', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_log_created_at'), table_name='error_log')
    op.drop_table('error_log')
    # ### end Alembic commands ###
